services:
  meshtastic_listener:
    depends_on:
      - listener_db
    build:
      context: .
      dockerfile: dockerfile
    container_name: meshtastic_listener
    user: "1000:1000"
    env_file:
      - .env
    restart: unless-stopped

  listener_db:
    image: mariadb
    restart: unless-stopped
    container_name: listener_db
    expose:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - listener_db
    restart: unless-stopped
    ports:
      - 8080:8080
