version: '3.8'
services:
  meshtastic_listener:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: meshtastic_listener
    volumes:
      - ./data:/home/meshtastic/data
    environment:
      # - DEVICE_INTERFACE=192.168.3.185 # only use if connecting via IP address
      - DB_NAME=listener.db
    # devices:
      # - /dev/ttyUSB0:/dev/ttyUSB0 # only use if connecting via USB
    restart: unless-stopped