services:
  meshtastic_listener:
    depends_on:
      - listener_db
    image: michaelgillett/meshtastic-listener:main
    volumes:
      - ./logs:/home/meshtastic/logs
    container_name: meshtastic_listener
    user: "1000:1000"
    env_file:
      - .env
    restart: unless-stopped

  listener_db:
    image: postgres:latest
    container_name: listener_db
    expose:
      - 5432:5432
    shm_size: 256mb
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - listener_db
    restart: unless-stopped
    ports:
      - 8080:8080
