services:
  meshtastic_listener:
    build:
      context: .
      dockerfile: dockerfile
    container_name: meshtastic_listener
    volumes:
      - ./data:/home/meshtastic/data
    user: "1000:1000"
    environment:
      - DB_NAME=listener.db
      # Change this to your device's IP address
      - DEVICE_INTERFACE=192.168.2.147
    # Uncomment if you need to access the serial port for a Meshtastic device
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    # group_add:
    #   - dialout
    restart: unless-stopped
