version: '3.8'
services:
  meshtastic_listener:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: meshtastic_listener
    volumes:
      - ./data:/home/meshtastic/data
    environment:
      - DB_NAME=listener.db
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped