"""reconnection-attempts

Revision ID: 0ec81cbefa1c
Revises: 2e128e7a45b5
Create Date: 2025-10-20 00:37:10.776065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec81cbefa1c'
down_revision: Union[str, None] = '2e128e7a45b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('reconnectAttempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'reconnectAttempts')
    # ### end Alembic commands ###
