"""no more categories

Revision ID: 1e489ac127b8
Revises: dd66d56da66b
Create Date: 2025-05-29 21:37:11.635745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e489ac127b8'
down_revision: Union[str, None] = 'dd66d56da66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bbs_messages')
    op.drop_constraint(op.f('nodes_selectedCategory_fkey'), 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'selectedCategory')
    op.drop_constraint(op.f('subscriptions_categoryId_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'categoryId')
    op.drop_table('bbs_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('subscriptions_categoryId_fkey'), 'subscriptions', 'bbs_categories', ['categoryId'], ['id'])
    op.add_column('nodes', sa.Column('selectedCategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('nodes_selectedCategory_fkey'), 'nodes', 'bbs_categories', ['selectedCategory'], ['id'])
    op.create_table('bbs_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fromId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('toId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('categoryId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('rxSnr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rxRssi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hopStart', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hopLimit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('readCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isDeleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['bbs_categories.id'], name=op.f('bbs_messages_categoryId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bbs_messages_pkey'))
    )
    op.create_table('bbs_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bbs_categories_pkey'))
    )
    # ### end Alembic commands ###
