"""remove hash table

Revision ID: 251820133a33
Revises: 9ca22844431a
Create Date: 2025-05-24 15:58:44.794126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251820133a33'
down_revision: Union[str, None] = '9ca22844431a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_hash_table')
    op.drop_column('bbs_messages', 'messageHash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbs_messages', sa.Column('messageHash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('db_hash_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash_value', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('db_hash_table_pkey'))
    )
    # ### end Alembic commands ###
