"""node alarm status table

Revision ID: 2830d07e289a
Revises: 1e489ac127b8
Create Date: 2025-05-30 22:45:05.729694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2830d07e289a'
down_revision: Union[str, None] = '1e489ac127b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_alarm_status',
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('temperatureAlarm', sa.Boolean(), nullable=True),
    sa.Column('humidityAlarm', sa.Boolean(), nullable=True),
    sa.Column('channelUsageAlarm', sa.Boolean(), nullable=True),
    sa.Column('batteryLevelAlarm', sa.Boolean(), nullable=True),
    sa.Column('networkPathAlarm', sa.Boolean(), nullable=True),
    sa.Column('errorRateAlarm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('nodeNum')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_alarm_status')
    # ### end Alembic commands ###
