"""alerts-modified

Revision ID: 2e128e7a45b5
Revises: 78c322405347
Create Date: 2025-10-19 21:32:46.179914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e128e7a45b5'
down_revision: Union[str, None] = '78c322405347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_settings', sa.Column('tracerouteFailureThreshold', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_settings', 'tracerouteFailureThreshold')
    # ### end Alembic commands ###
