"""system-stats

Revision ID: 514e6cccf531
Revises: cae47a32b688
Create Date: 2025-10-24 02:26:59.054677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514e6cccf531'
down_revision: Union[str, None] = 'cae47a32b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_settings', sa.Column('cpuUsageThreshold', sa.Float(), nullable=False, server_default='90.0'))
    op.add_column('alert_settings', sa.Column('memoryUsageThreshold', sa.Float(), nullable=False, server_default='90.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_settings', 'memoryUsageThreshold')
    op.drop_column('alert_settings', 'cpuUsageThreshold')
    # ### end Alembic commands ###
