"""traceroute table for tracking tx and rx

Revision ID: 60b036253c1a
Revises: 2e947dcd2c56
Create Date: 2025-06-02 21:50:09.531577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b036253c1a'
down_revision: Union[str, None] = '2e947dcd2c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempted_traceroutes')
    op.add_column('traceroutes', sa.Column('tracerouteId', sa.Integer(), nullable=False))
    op.add_column('traceroutes', sa.Column('txTime', sa.BigInteger(), nullable=True))
    op.alter_column('traceroutes', 'rxTime',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('traceroutes', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traceroutes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('traceroutes', 'rxTime',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('traceroutes', 'txTime')
    op.drop_column('traceroutes', 'tracerouteId')
    op.create_table('attempted_traceroutes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('toId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('attempted_traceroutes_pkey'))
    )
    # ### end Alembic commands ###
