"""traceroute table for tracking tx and rx

Revision ID: 61669993f213
Revises: 2e947dcd2c56
Create Date: 2025-06-02 21:23:53.140017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61669993f213'
down_revision: Union[str, None] = '2e947dcd2c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traceroutes', sa.Column('tracerouteId', sa.BigInteger(), nullable=True))
    op.add_column('traceroutes', sa.Column('txTime', sa.BigInteger(), nullable=True))
    op.alter_column('traceroutes', 'rxTime',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traceroutes', 'rxTime',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('traceroutes', 'txTime')
    op.drop_column('traceroutes', 'tracerouteId')
    # ### end Alembic commands ###
