"""drop hashing table

Revision ID: 6be792646ccf
Revises: 9ca22844431a
Create Date: 2025-05-24 14:35:39.853637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be792646ccf'
down_revision: Union[str, None] = '9ca22844431a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_nodes',
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('nodeNum')
    )
    op.create_table('bbs_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('batteryLevel', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('channelUtilization', sa.Float(), nullable=True),
    sa.Column('uptimeSeconds', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('relativeHumidity', sa.Float(), nullable=True),
    sa.Column('barometricPressure', sa.Float(), nullable=True),
    sa.Column('gasResistance', sa.Float(), nullable=True),
    sa.Column('iaq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('fromId', sa.BigInteger(), nullable=False),
    sa.Column('toId', sa.BigInteger(), nullable=False),
    sa.Column('portnum', sa.String(length=75), nullable=False),
    sa.Column('packetRaw', sa.JSON(), nullable=False),
    sa.Column('rxSnr', sa.Float(), nullable=True),
    sa.Column('rxRssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.Integer(), nullable=False),
    sa.Column('sourceNodeId', sa.BigInteger(), nullable=False),
    sa.Column('neighborNodeId', sa.BigInteger(), nullable=False),
    sa.Column('snr', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outgoing_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('toId', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('txId', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceroutes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('fromId', sa.BigInteger(), nullable=False),
    sa.Column('toId', sa.BigInteger(), nullable=False),
    sa.Column('tracerouteDetails', sa.JSON(), nullable=True),
    sa.Column('snrAvg', sa.Float(), nullable=True),
    sa.Column('directConnection', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('airUtilTx', sa.Float(), nullable=True),
    sa.Column('numPacketsTx', sa.Integer(), nullable=True),
    sa.Column('numPacketsRx', sa.Integer(), nullable=True),
    sa.Column('numPacketsRxBad', sa.Integer(), nullable=True),
    sa.Column('numOnlineNodes', sa.Integer(), nullable=True),
    sa.Column('numTotalNodes', sa.Integer(), nullable=True),
    sa.Column('numRxDupe', sa.Integer(), nullable=True),
    sa.Column('numTxRelay', sa.Integer(), nullable=True),
    sa.Column('numTxRelayCanceled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.BigInteger(), nullable=False),
    sa.Column('latitudeI', sa.BigInteger(), nullable=True),
    sa.Column('longitudeI', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bbs_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BigInteger(), nullable=False),
    sa.Column('fromId', sa.BigInteger(), nullable=False),
    sa.Column('toId', sa.BigInteger(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('rxSnr', sa.Float(), nullable=False),
    sa.Column('rxRssi', sa.Integer(), nullable=False),
    sa.Column('hopStart', sa.Integer(), nullable=False),
    sa.Column('hopLimit', sa.Integer(), nullable=False),
    sa.Column('readCount', sa.Integer(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['bbs_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('longName', sa.String(length=100), nullable=True),
    sa.Column('shortName', sa.String(length=4), nullable=True),
    sa.Column('macAddr', sa.String(length=100), nullable=True),
    sa.Column('hwModel', sa.String(length=100), nullable=True),
    sa.Column('publicKey', sa.String(length=100), nullable=True),
    sa.Column('nodeRole', sa.String(length=100), nullable=True),
    sa.Column('lastHeard', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('precisionBits', sa.Integer(), nullable=True),
    sa.Column('hopsAway', sa.Integer(), nullable=True),
    sa.Column('selectedCategory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selectedCategory'], ['bbs_categories.id'], ),
    sa.PrimaryKeyConstraint('nodeNum')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodeNum', sa.BigInteger(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('isSubscribed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['bbs_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('db_hash_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_hash_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash_value', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('db_hash_table_pkey'))
    )
    op.drop_table('subscriptions')
    op.drop_table('nodes')
    op.drop_table('bbs_messages')
    op.drop_table('waypoints')
    op.drop_table('transmission_metrics')
    op.drop_table('traceroutes')
    op.drop_table('outgoing_notifications')
    op.drop_table('neighbors')
    op.drop_table('message_history')
    op.drop_table('environment_metrics')
    op.drop_table('device_metrics')
    op.drop_table('bbs_categories')
    op.drop_table('admin_nodes')
    # ### end Alembic commands ###
