"""hostLastHeard-alertSettings

Revision ID: 78c322405347
Revises: eb32b6495943
Create Date: 2025-10-14 15:11:42.258900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c322405347'
down_revision: Union[str, None] = 'eb32b6495943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channelUsageThreshold', sa.Float(), nullable=False),
    sa.Column('highTempThreshold', sa.Float(), nullable=False),
    sa.Column('lowTempThreshold', sa.Float(), nullable=False),
    sa.Column('highHumidityThreshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nodes', sa.Column('hostLastHeard', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'hostLastHeard')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
