"""make id be unique

Revision ID: 9f07ab7df693
Revises: 71225e3b912e
Create Date: 2025-06-03 08:08:54.809644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f07ab7df693'
down_revision: Union[str, None] = '71225e3b912e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'traceroutes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traceroutes', type_='unique')
    # ### end Alembic commands ###
