"""remove-message-history

Revision ID: cae47a32b688
Revises: 0ec81cbefa1c
Create Date: 2025-10-20 21:06:29.447639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cae47a32b688'
down_revision: Union[str, None] = '0ec81cbefa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rxTime', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fromId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('toId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('portnum', sa.VARCHAR(length=75), autoincrement=False, nullable=False),
    sa.Column('packetRaw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rxSnr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rxRssi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('message_history_pkey'))
    )
    # ### end Alembic commands ###
