"""is software host

Revision ID: d496910789c9
Revises: 251820133a33
Create Date: 2025-05-28 19:55:56.307571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd496910789c9'
down_revision: Union[str, None] = '251820133a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('isHost', sa.Boolean(), nullable=True))
    op.add_column('nodes', sa.Column('hostSoftwareVersion', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'hostSoftwareVersion')
    op.drop_column('nodes', 'isHost')
    # ### end Alembic commands ###
