"""remove alert table v1

Revision ID: eb32b6495943
Revises: 752c04bd34dc
Create Date: 2025-06-04 04:08:06.793466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb32b6495943'
down_revision: Union[str, None] = '752c04bd34dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_alarm_status')
    op.create_unique_constraint(None, 'traceroutes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traceroutes', type_='unique')
    op.create_table('node_alarm_status',
    sa.Column('nodeNum', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('temperatureAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('humidityAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('channelUsageAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('batteryLevelAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('networkPathAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('errorRateAlarm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nodeNum', name=op.f('node_alarm_status_pkey'))
    )
    # ### end Alembic commands ###
